event_inherited()
idle_timer = time_source_create(time_source_game,idle_time,time_source_units_seconds,idle_complete);
attack_windup_timer = time_source_create(time_source_game,attack_windup_time,time_source_units_seconds,attack_windup_complete);
attack_timer = time_source_create(time_source_game,attack_time,time_source_units_seconds,attack_complete);

array_push(time_sources,idle_timer,attack_windup_timer,attack_timer);

